# Ejercicio 3.7 - Pandas (Estructuras de datos, +Pandas)

**Materia:** Machine Learning - PAO25/26 Nocturna
**Profesor:** Elvis Pachacama
**Estudiante:** Omar Recalde Suarez
**Repositorio:** https://github.com/OmaRecalde/machinelearning2026

## Contenido
Transcripción del material "PAO25_25_08_Python_+Pandas": búsqueda y filtrado (isin, masks), ordenación (sort_index, sort_values), ranking, operaciones matemáticas entre objetos, operaciones entre Series y DataFrames, funciones lambda con apply, estadística descriptiva, agregaciones (groupby), y correlaciones (con ejemplo práctico del dataset Auto MPG).

# 📊 Operaciones Avanzadas en Pandas (Parte 2)

## Sección 1: Búsqueda, Verificación de Valores y Conteo de Elementos

En esta sección aprenderemos a auditar un `DataFrame` para verificar la existencia de variables específicas, mapear la presencia de un listado de valores usando máscaras booleanas y cuantificar el total de registros que cumplen con condiciones de umbral.

### 📌 Conceptos Clave:
* **Operador `in`:** Valida de forma nativa si una etiqueta o nombre de columna se encuentra registrado en el esquema de claves del `DataFrame`.
* **Método `.isin([valores])`:** Genera una matriz booleana (máscara) indicando qué coordenadas contienen elementos que coinciden con la lista suministrada.
* **Capa subyacente NumPy:** Al encadenar `.values`, se extrae el array primitivo de NumPy subyacente en Pandas, facilitando operaciones vectorizadas veloces como sumatorias totales (`.sum()`).

In [1]:
import numpy as np
import pandas as pd

# =====================================================================
# 1. CONFIGURACIÓN INICIAL Y GENERACIÓN DE MATRIZ ALEATORIA
# =====================================================================
print(f"[INFO] Versión de Pandas en uso: {pd.__version__}")

# Fijamos una semilla aleatoria interna para reproducibilidad en tus pruebas
np.random.seed(42)

# Generamos una matriz aleatoria de enteros entre 0 y 5 con dimensiones 2x3
rand_matrix = np.random.randint(6, size=(2, 3))
frame = pd.DataFrame(rand_matrix, columns=list('ABC'))

print("\n--- DataFrame Base de Búsqueda ---")
display(frame)


# =====================================================================
# 2. BÚSQUEDA DE COLUMNAS (VERIFICACIÓN DE ESQUEMA)
# =====================================================================
# El DataFrame evalúa por defecto sobre sus ejes de columnas (claves)
existe_columna = 'A' in frame
print(f"\n¿Existe la columna 'A' en el DataFrame?: {existe_columna}")


# =====================================================================
# 3. VERIFICACIÓN DE VALORES ESPECÍFICOS CON .isin()
# =====================================================================
# Mapeamos la presencia de los números 2 o 3 dentro de toda la estructura
mascara_presencia = frame.isin([3, 2])
print("\n--- Máscara Booleana de Presencia (.isin([3, 2])) ---")
display(mascara_presencia)


# =====================================================================
# 4. CUANTIFICACIÓN COMPLETA DE OCURRENCIAS
# =====================================================================
# Contar exactamente cuántos elementos en el DataFrame son iguales a 4
total_cuatros = frame.isin([4]).values.sum()
print(f"\nCantidad total de valores '4' encontrados: {total_cuatros}")

# Evaluar condiciones relacionales numéricas combinadas con sumatorias
# ¿Cuántos valores son mayores o iguales a 2?
mask_umbral = frame >= 2
total_mayores_dos = mask_umbral.values.sum()

print("\n--- Criterio de Evaluación Relacional (>= 2) ---")
print(f"Total de celdas que cumplen la condición: {total_mayores_dos}")
display(mask_umbral)

[INFO] Versión de Pandas en uso: 2.3.2

--- DataFrame Base de Búsqueda ---

   A  B  C
0  3  4  2
1  4  4  1

¿Existe la columna 'A' en el DataFrame?: True

--- Máscara Booleana de Presencia (.isin([3, 2])) ---

       A      B      C
0   True  False   True
1  False  False  False

Cantidad total de valores '4' encontrados: 3

--- Criterio de Evaluación Relacional (>= 2) ---
Total de celdas que cumplen la condición: 5

      A     B      C
0  True  True   True
1  True  True  False

## Sección 2: Técnicas de Ordenación (Sorting) y Ranking de Datos

En este bloque analizaremos cómo reordenar las estructuras tabulares bajo criterios jerárquicos y cómo establecer rankings numéricos basados en los valores de las variables.

### 📌 Conceptos Clave:
* **`.sort_index()`**: Reordena las filas o columnas según sus etiquetas de índice o nombres. El parámetro `axis=1` se usa para ordenar alfabéticamente las columnas[cite: 3].
* **`.sort_values(by=...)`**: Ordena las observaciones basándose en los valores reales de una o más columnas[cite: 3]. Si se pasa `axis=1`, ordena las columnas de acuerdo con los valores de una fila específica[cite: 3].
* **`inplace=True`**: Modifica la estructura de forma definitiva en memoria sin necesidad de reasignar la variable[cite: 3].
* **`.rank(method='max')`**: Asigna posiciones numéricas (rankings) a los elementos[cite: 3]. El método `'max'` gestiona empates asignando la posición máxima del grupo repetido[cite: 3].

In [2]:
from random import shuffle
import numpy as np
import pandas as pd

# =====================================================================
# 1. CREACIÓN DEL DATAFRAME CON ÍNDICES MEZCLADOS
# =====================================================================
np.random.seed(10)
rand_matrix = np.random.randint(20, size=(5, 4))

# Generamos una lista de índices y la mezclamos aleatoriamente
indices = list(range(5))
shuffle(indices)

# Creamos el DataFrame con columnas desordenadas alfabéticamente
df_desordenado = pd.DataFrame(rand_matrix, columns=list('DACB'), index=indices)
print("--- DataFrame Original (Índices y Columnas Desordenadas) ---")
display(df_desordenado)


# =====================================================================
# 2. ORDENACIÓN POR ÍNDICES Y EJES
# =====================================================================

# Ordenar las filas por su índice semántico en orden descendente (De mayor a menor)
print("\n--- Ordenado por Índice de Filas Descendente (.sort_index) ---")
display(df_desordenado.sort_index(ascending=False))

# Ordenar las columnas alfabéticamente (axis=1) en orden descendente (D -> C -> B -> A)
print("\n--- Ordenado por Eje de Columnas Descendente (axis=1) ---")
display(df_desordenado.sort_index(axis=1, ascending=False))


# =====================================================================
# 3. ORDENACIÓN POR VALORES CONCRETOS
# =====================================================================

# Ordenar las filas de menor a mayor tomando como referencia los valores de la columna 'A'
print("\n--- Filas Ordenadas Ascendentemente por los valores de la columna 'A' ---")
display(df_desordenado.sort_values(by='A', ascending=True))

# Aplicar ordenación persistente en memoria usando inplace=True
df_desordenado.sort_values(by='A', ascending=False, inplace=True)
print("\n--- DataFrame Modificado en Memoria (Orden Descendente por 'A') ---")
display(df_desordenado)


# =====================================================================
# 4. RANKING E ITERACIÓN DE VALORES ORDERADOS
# =====================================================================

# Construir un ranking posicional por filas (axis=1) con método de resolución 'max'
print("\n--- Ranking de Valores por Filas (.rank) ---")
display(df_desordenado.rank(method='max', axis=1))

# Imprimir los valores de la columna 'C' ordenados de mayor a menor uno por uno
print("\n--- Bucle: Valores de la columna 'C' ordenados de Mayor a Menor ---")
for valor in df_desordenado.sort_values(by='C', ascending=False)['C'].values:
    print(f"Valor extraído de C: {valor}")

--- DataFrame Original (Índices y Columnas Desordenadas) ---

    D   A   C  B
4   9   4  15  0
2  17  16  17  8
0   9   0  10  8
1   4  19  16  4
3  15  11  11  1

--- Ordenado por Índice de Filas Descendente (.sort_index) ---

    D   A   C  B
4   9   4  15  0
3  15  11  11  1
2  17  16  17  8
1   4  19  16  4
0   9   0  10  8

--- Ordenado por Eje de Columnas Descendente (axis=1) ---

    D   C  B   A
4   9  15  0   4
2  17  17  8  16
0   9  10  8   0
1   4  16  4  19
3  15  11  1  11

--- Filas Ordenadas Ascendentemente por los valores de la columna 'A' ---

    D   A   C  B
0   9   0  10  8
4   9   4  15  0
3  15  11  11  1
2  17  16  17  8
1   4  19  16  4

--- DataFrame Modificado en Memoria (Orden Descendente por 'A') ---

    D   A   C  B
1   4  19  16  4
2  17  16  17  8
3  15  11  11  1
4   9   4  15  0
0   9   0  10  8

--- Ranking de Valores por Filas (.rank) ---

     D    A    C    B
1  2.0  4.0  3.0  2.0
2  4.0  2.0  4.0  1.0
3  4.0  3.0  3.0  1.0
4  3.0  2.0  4.0  1.0
0  3.0  1.0  4.0  2.0

--- Bucle: Valores de la columna 'C' ordenados de Mayor a Menor ---
Valor extraído de C: 17
Valor extraído de C: 16
Valor extraído de C: 15
Valor extraído de C: 11
Valor extraído de C: 10

## Sección 3: Operaciones Aritméticas, Alineación de Índices y Difusión (Broadcasting)

En esta sección analizaremos cómo interactúan dos matrices de distintas dimensiones al realizar operaciones matemáticas estándar y cómo usar métodos explícitos para controlar la introducción de valores nulos (NaN).

### 📌 Conceptos Clave:
* **Alineación por Índices:** Al sumar, restar o multiplicar DataFrames, Pandas empareja las filas y columnas que tengan exactamente el mismo nombre. Si no coinciden, introduce de forma predeterminada un `NaN`.
* **Parámetro `fill_value`:** Permite especificar un valor por defecto (como `0`) para rescatar los datos en caso de que una de las celdas no exista en la otra matriz[cite: 3].
* **Broadcasting (Difusión):** Operación matemática que permite restar o sumar una sola fila (`Series`) a todo el `DataFrame` completo, repitiendo la operación renglón por renglón de manera automatizada[cite: 3].

In [3]:
import numpy as np
import pandas as pd

# =====================================================================
# 1. OPERACIONES MATEMÁTICAS ESTÁNDAR ENTRE DATAFRAMES SIMÉTRICOS
# =====================================================================
np.random.seed(20)

matrixA = np.random.randint(100, size=(4, 4))
matrixB = np.random.randint(100, size=(4, 4))

frameA = pd.DataFrame(matrixA)
frameB = pd.DataFrame(matrixB)

print("--- DataFrame A ---")
display(frameA)
print("\n--- DataFrame B ---")
display(frameB)

# Suma mediante operadores aritméticos convencionales (+) y métodos explícitos (.add)
print("\n--- Resultado de la Suma (Sintaxis Equivalentes) ---")
display(frameA + frameB)

# Resta mediante operadores aritméticos convencionales (-) y métodos explícitos (.sub)
print("\n--- Resultado de la Resta (frameB - frameA) ---")
display(frameB.sub(frameA))


# =====================================================================
# 2. ALINEACIÓN ASIMÉTRICA Y USO DE FILL_VALUE
# =====================================================================
# Creamos una tercera matriz más pequeña (dimensiones 3x3)
frameC = pd.DataFrame(np.random.randint(100, size=(3, 3)))

print("\n--- DataFrame C (Asimétrico 3x3) ---")
display(frameC)

# La suma directa generará valores NaN en la cuarta fila y cuarta columna (índices 3)
print("\n--- Suma Incompleta Directa (Aparición de NaNs) ---")
display(frameC + frameA)

# SOLUCIÓN DE CONTROL: Usar .add() especificando fill_value=0 para rescatar los datos huérfanos
print("\n--- Suma Controlada de forma Segura (.add con fill_value=0) ---")
display(frameA.add(frameC, fill_value=0))


# =====================================================================
# 3. OPERACIONES ENTRE SERIES Y DATAFRAMES (BROADCASTING)
# =====================================================================
# Uso común en analítica: Averiguar la diferencia o desviación de cada fila frente a un patrón
rand_matrix = np.random.randint(10, size=(3, 4))
df = pd.DataFrame(rand_matrix, columns=list('ABCD'))

print("\n--- DataFrame Base para Difusión ---")
display(df)

# Extraemos la primera fila (Índice posicional 0), la cual se convierte en una Series
primera_fila = df.iloc[0]
print("\n--- Fila de Referencia (Series de la fila 0) ---")
display(primera_fila)

# Restar la primera fila a todas las filas del DataFrame (Broadcasting por filas)
print("\n--- Desviación del DataFrame con respecto a la Fila 0 (Eje Horizontal) ---")
display(df - primera_fila)

# Restar una columna completa a todas las columnas usando .sub() especificando axis=0
print("\n--- Desviación con respecto a la columna 'A' (Eje Vertical, axis=0) ---")
display(df.sub(df['A'], axis=0))

--- DataFrame A ---

    0   1   2   3
0  99  90  15  95
1  28  90   9  20
2  75  22  71  34
3  96  40  85  90

--- DataFrame B ---

    0   1   2   3
0  26  83  16  62
1  16   7  98   6
2  26  13  75  58
3  25   3  74  75

--- Resultado de la Suma (Sintaxis Equivalentes) ---

     0    1    2    3
0  125  173   31  157
1   44   97  107   26
2  101   35  146   92
3  121   43  159  165

--- Resultado de la Resta (frameB - frameA) ---

    0   1   2   3
0 -73  -7   1 -33
1 -12 -83  89 -14
2 -49  -9   4  24
3 -71 -37 -11 -15

--- DataFrame C (Asimétrico 3x3) ---

    0   1   2
0  61  77  83
1  57  94  32
2  10   6  75

--- Suma Incompleta Directa (Aparición de NaNs) ---

       0      1      2   3
0  160.0  167.0   98.0 NaN
1   85.0  184.0   41.0 NaN
2   85.0   28.0  146.0 NaN
3    NaN    NaN    NaN NaN

--- Suma Controlada de forma Segura (.add con fill_value=0) ---

       0      1      2     3
0  160.0  167.0   98.0  95.0
1   85.0  184.0   41.0  20.0
2   85.0   28.0  146.0  34.0
3   96.0   40.0   85.0  90.0

--- DataFrame Base para Difusión ---

   A  B  C  D
0  2  3  1  8
1  0  2  7  6
2  6  8  2  1

--- Fila de Referencia (Series de la fila 0) ---

A    2
B    3
C    1
D    8
Name: 0, dtype: int64

--- Desviación del DataFrame con respecto a la Fila 0 (Eje Horizontal) ---

   A  B  C  D
0  0  0  0  0
1 -2 -1  6 -2
2  4  5  1 -7

--- Desviación con respecto a la columna 'A' (Eje Vertical, axis=0) ---

   A  B  C  D
0  0  1 -1  6
1  0  2  7  6
2  0  2 -4 -5

## Sección 4: Funciones Lambda a Medida y Estadísticas Descriptivas

En esta sección estudiaremos cómo vectorizar transformaciones personalizadas sobre los ejes de una matriz y cómo perfilar un conjunto de datos extrayendo métricas estadísticas agregadas.

### 📌 Conceptos Clave:
* **`.apply(lambda)`:** Aplica una función anónima (o personalizada) a lo largo de un eje del DataFrame.
  * `axis=0` (Por defecto): Procesa los datos columna por columna[cite: 3].
  * `axis=1`: Procesa los datos fila por fila[cite: 3].
* **`idxmax()` / `idxmin()`:** Devuelven el **índice semántico** (la etiqueta) donde se localiza el valor máximo o mínimo absoluto de una variable[cite: 3].
* **`numeric_only=True`:** Restringe los cálculos aritméticos y estadísticos exclusivamente a columnas numéricas, ignorando automáticamente variables de texto (como nombres o géneros) para evitar errores sintácticos[cite: 3].

In [4]:
import numpy as np
import pandas as pd

# =====================================================================
# 1. APLICACIÓN DE FUNCIONES PERSONALIZADAS (LAMBDA)
# =====================================================================
np.random.seed(30)
rand_matrix = np.random.randint(10, size=(3, 4))
df_lambda = pd.DataFrame(rand_matrix, columns=list('ABCD'))

print("--- DataFrame Base para Funciones Lambda ---")
display(df_lambda)

# Ejemplo 1: Calcular el rango (Máximo - Mínimo) de cada FILA usando axis=1
rango_filas = df_lambda.apply(lambda x: x.max() - x.min(), axis=1)
print("\n--- Rango numérico calculado por cada FILA (axis=1) ---")
print(rango_filas)

# Ejemplo 2: Calcular el rango usando una función explícita por COLUMNA usando axis=0
def calcular_rango_columna(columna):
    return columna.max() - columna.min()

rango_columnas = df_lambda.apply(calcular_rango_columna, axis=0)
print("\n--- Rango numérico calculado por cada COLUMNA (axis=0) ---")
print(rango_columnas)


# =====================================================================
# 2. ESTADÍSTICA DESCRIPTIVA EN ACCIÓN
# =====================================================================
# Construcción de un DataFrame heterogéneo (Texto, Números, Nulos)
diccionario = { 
    "nombre": ["Marisa", "Laura", "Manuel", "Carlos"], 
    "edad": [34, 34, 11, 30],
    "puntos": [98, 12, 98, np.nan], 
    "genero": ["F", "F", "M", "M"]
}
frame_estudiantes = pd.DataFrame(diccionario)

print("\n--- DataFrame de Estudiantes ---")
display(frame_estudiantes)

# .describe() genera un resumen estadístico instantáneo de las variables numéricas
print("\n--- Resumen Estadístico Estándar (.describe()) ---")
display(frame_estudiantes.describe())

# Sumatoria vertical restringida a datos numéricos (numeric_only=True)
print("\n--- Sumatoria total de las columnas numéricas ---")
print(frame_estudiantes.sum(axis=0, numeric_only=True))

# Desviación estándar de una columna específica
desviacion_edad = frame_estudiantes['edad'].std()
print(f"\nDesviación estándar de la variable 'edad': {desviacion_edad:.2f}")


# =====================================================================
# 3. BÚSQUEDA FILTRADA POR ÍNDICES CRÍTICOS (MÁXIMOS Y MÍNIMOS)
# =====================================================================

# Identificar el índice semántico de la persona con la edad más alta
indice_max_edad = frame_estudiantes['edad'].idxmax()
print(f"\nÍndice semántico del estudiante con mayor edad: {indice_max_edad} (Fila {indice_max_edad})")

# EXTRAER LA FILA COMPLETA que contenga el valor máximo de una columna
valor_max_puntos = frame_estudiantes['puntos'].max()
print(f"\nPuntuación máxima registrada: {valor_max_puntos}")

print("\n--- Registro(s) del estudiante con el puntaje máximo obtenido ---")
# Filtramos buscando las filas que coincidan exactamente con dicho valor máximo
filas_max_puntaje = frame_estudiantes[frame_estudiantes['puntos'] == valor_max_puntos]
display(filas_max_puntaje)

--- DataFrame Base para Funciones Lambda ---

   A  B  C  D
0  5  5  4  7
1  2  5  1  3
2  9  7  7  1

--- Rango numérico calculado por cada FILA (axis=1) ---
0    3
1    4
2    8
dtype: int64

--- Rango numérico calculado por cada COLUMNA (axis=0) ---
A    7
B    2
C    6
D    6
dtype: int64

--- DataFrame de Estudiantes ---

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F
2  Manuel    11    98.0      M
3  Carlos    30     NaN      M

--- Resumen Estadístico Estándar (.describe()) ---

            edad     puntos
count   4.000000   3.000000
mean   27.250000  69.333333
std    10.996211  49.652123
min    11.000000  12.000000
25%    25.250000  55.000000
50%    32.000000  98.000000
75%    34.000000  98.000000
max    34.000000  98.000000

--- Sumatoria total de las columnas numéricas ---
edad      109.0
puntos    208.0
dtype: float64

Desviación estándar de la variable 'edad': 11.00

Índice semántico del estudiante con mayor edad: 0 (Fila 0)

Puntuación máxima registrada: 98.0

--- Registro(s) del estudiante con el puntaje máximo obtenido ---

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
2  Manuel    11    98.0      M

## Sección 5: Agregaciones (`groupby`), Filtrado Colectivo y Matriz de Correlación

En esta sección estudiaremos cómo agrupar información categórica, extraer resúmenes por segmentos y calcular la correlación lineal entre variables para identificar dependencias numéricas.

### 📌 Conceptos Clave:
* **`.groupby('columna')`:** Segmenta el DataFrame en grupos basados en los valores únicos de la columna especificada.
* **`.aggregate(['min', 'mean', 'max'])`:** Permite calcular múltiples estadísticos descriptivos en una sola línea de código sobre las columnas seleccionadas.
* **`.filter(funcion)`:** Evalúa una condición lógica sobre todo el grupo completo (por ejemplo, si la media del grupo supera un umbral) y descarta los registros de los grupos que no la cumplan[cite: 3].
* **`.corr(numeric_only=True)`:** Devuelve una matriz que mide el grado de relación lineal entre las variables numéricas (valores entre -1 y 1)[cite: 3].

In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Recuperamos el DataFrame de estudiantes de la sección anterior
diccionario = { 
    "nombre": ["Marisa", "Laura", "Manuel", "Carlos"], 
    "edad": [34, 34, 11, 30],
    "puntos": [98, 12, 98, np.nan], 
    "genero": ["F", "F", "M", "M"]
}
frame_estudiantes = pd.DataFrame(diccionario)


# =====================================================================
# 1. AGREGACIONES AGRUPADAS CON GROUPBY
# =====================================================================

print("--- Conteo de Registros por Género ---")
# Agrupamos por género y contamos los elementos no nulos
display(frame_estudiantes.groupby('genero').count())

print("\n--- Múltiples Estadísticos Simultáneos (.aggregate) ---")
# Agrupamos por género y obtenemos min, media y max de edad y puntos
estadisticas_grupo = frame_estudiantes.groupby('genero')[['edad', 'puntos']].aggregate(['min', 'mean', 'max'])
display(estadisticas_grupo)


# =====================================================================
# 2. FILTRADO LÓGICO DE GRUPOS COMPLETOS
# =====================================================================

# Definimos una función que evalúa si la media de edad de un grupo es mayor a 30
def evaluar_media_edad(grupo):
    return grupo["edad"].mean() > 30

print("\n--- Filtrado de Grupos (Solo géneros con promedio de edad > 30) ---")
df_filtrado_grupo = frame_estudiantes.groupby('genero').filter(evaluar_media_edad)
display(df_filtrado_grupo)


# =====================================================================
# 3. CASO REAL: ANÁLISIS DE CORRELACIONES (AUTO MPG DATASET)
# =====================================================================

# Ingesta remota segura del dataset de eficiencia de combustible de vehículos
path_url = 'http://archive.ics.uci.edu/ml/machine-learning-databases/auto-mpg/auto-mpg.data'
mpg_data = pd.read_csv(
    path_url, 
    sep='\s+', 
    header=None,
    names=['mpg', 'cilindros', 'desplazamiento', 'potencia', 'peso', 'aceleracion', 'año', 'origen', 'nombre'],
    na_values='?', 
    engine='c'
)

print("\n--- Muestra Aleatoria de la Eficiencia de Motores (Auto MPG) ---")
display(mpg_data.sample(3))

print("\n--- Matriz Completa de Correlación Numérica ---")
# Eliminamos columnas contextuales ('año', 'origen') para enfocar el análisis matemático
matriz_corr = mpg_data.drop(['año', 'origen'], axis=1).corr(numeric_only=True)
display(matriz_corr)

# Aplicamos un gradiente de color (estilo mapa de calor) para identificar correlaciones visualmente
print("\n[INFO] Desplegando representación gráfica de la matriz de correlación...")
display(matriz_corr.style.background_gradient(cmap=plt.get_cmap('RdYlGn'), axis=1))


# =====================================================================
# 🌟 EJERCICIO MODELO (PLANTILLA TIPO EXAMEN)
# =====================================================================
# Problema representativo de "100 Pandas Puzzles": 
# "Dado un DataFrame numérico, restar la media de cada fila a cada elemento de dicha fila"
print("\n--- 📝 EJERCICIO MODELO: Normalización por Resta de Media de Filas ---")

np.random.seed(42)
df_ejercicio = pd.DataFrame(np.random.randint(1, 10, size=(3, 3)), columns=list('XYZ'))
print("DataFrame Original del Ejercicio:")
display(df_ejercicio)

# Calculamos el promedio horizontal de cada fila (axis=1)
media_filas = df_ejercicio.mean(axis=1)

# Usamos el método .sub indicando el eje vertical axis=0 para aplicar la resta fila por fila
df_normalizado = df_ejercicio.sub(media_filas, axis=0)
print("\nDataFrame Resultante (Cada celda restada el promedio de su propia fila):")
display(df_normalizado)

<>:50: SyntaxWarning: invalid escape sequence '\s'
<>:50: SyntaxWarning: invalid escape sequence '\s'
/var/folders/2m/gslt1sdd4jv97ln34m3c388r0000gn/T/ipykernel_22868/2141678793.py:50: SyntaxWarning: invalid escape sequence '\s'
  sep='\s+',
Matplotlib is building the font cache; this may take a moment.

--- Conteo de Registros por Género ---

        nombre  edad  puntos
genero
F            2     2       2
M            2     2       1

--- Múltiples Estadísticos Simultáneos (.aggregate) ---

       edad           puntos
        min  mean max    min  mean   max
genero
F        34  34.0  34   12.0  55.0  98.0
M        11  20.5  30   98.0  98.0  98.0

--- Filtrado de Grupos (Solo géneros con promedio de edad > 30) ---

   nombre  edad  puntos genero
0  Marisa    34    98.0      F
1   Laura    34    12.0      F

--- Muestra Aleatoria de la Eficiencia de Motores (Auto MPG) ---

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion,año,origen,nombre
74,13.0,8,302.0,140.0,4294.0,16.0,72,1,ford gran torino (sw)
322,46.6,4,86.0,65.0,2110.0,17.9,80,3,mazda glc
201,18.5,6,250.0,110.0,3645.0,16.2,76,1,pontiac ventura sj

--- Matriz Completa de Correlación Numérica ---

,mpg,cilindros,desplazamiento,potencia,peso,aceleracion
mpg,1.000000,-0.775396,-0.804203,-0.778427,-0.831741,0.420289
cilindros,-0.775396,1.000000,0.950721,0.842983,0.896017,-0.505419
desplazamiento,-0.804203,0.950721,1.000000,0.897257,0.932824,-0.543684
potencia,-0.778427,0.842983,0.897257,1.000000,0.864538,-0.689196
peso,-0.831741,0.896017,0.932824,0.864538,1.000000,-0.417457
aceleracion,0.420289,-0.505419,-0.543684,-0.689196,-0.417457,1.000000

[INFO] Desplegando representación gráfica de la matriz de correlación...

--- 📝 EJERCICIO MODELO: Normalización por Resta de Media de Filas ---
DataFrame Original del Ejercicio:

   X  Y  Z
0  7  4  8
1  5  7  3
2  7  8  5

DataFrame Resultante (Cada celda restada el promedio de su propia fila):

          X         Y         Z
0  0.666667 -2.333333  1.666667
1  0.000000  2.000000 -2.000000
2  0.333333  1.333333 -1.666667